[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"JLink" 
[CONFIGURATIONS]
"Debug" 
"Release" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"JLink" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"DefaultSession" 
"JLink" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Release]
"DefaultSession" 
"JLink" 
[GENERAL_DATA_CONFIGURATION_SESSION_Release_JLink]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_JLink]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_DefaultSession]
[GENERAL_DATA_SESSION_JLink]
[END]
